"""Export a reference trajectory for the C++ engine to be validated against.

    ./venv/bin/python -m validation.export_reference

Writes tests/data/reference_trajectory.csv, which tests/cpp/test_core.cpp
replays. The C++ engine runs the same scenario with the same integrator at the
same timestep and has to reproduce these positions to ~1e-12 AU; anything
larger is a real difference in the physics rather than a rounding artifact.
"""

import pathlib

import numpy as np

from validation.nbody import angular_momentum, total_energy
from validation.scenarios import sun_earth
from validation.simulate import run

# Must match kDt in scenes/orbital/main.cpp and the value in test_core.cpp.
DT = 1.0 / 365.25  # one day, in years
DURATION = 2.0     # years
INTEGRATOR = "verlet"

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "tests" / "data"


def main():
    scenario = sun_earth()
    result = run(scenario, INTEGRATOR, dt=DT, duration=DURATION)

    OUTPUT.mkdir(parents=True, exist_ok=True)
    path = OUTPUT / "reference_trajectory.csv"

    n = len(scenario.masses)
    header = ["t"]
    for i in range(n):
        header += [f"x{i}", f"y{i}", f"z{i}"]

    with open(path, "w") as f:
        f.write(f"# generated by validation/export_reference.py -- do not edit\n")
        f.write(f"# integrator={INTEGRATOR} dt={DT!r} duration={DURATION!r}\n")
        f.write(",".join(header) + "\n")

        for step in range(len(result.times)):
            row = [f"{result.times[step]:.17g}"]
            for i in range(n):
                x, y = result.trajectory[step, i]
                row += [f"{x:.17g}", f"{y:.17g}", "0"]  # 2D Python -> 3D C++
            f.write(",".join(row) + "\n")

    # Printed because the C++ diagnostics tests use these as fixtures.
    s = sun_earth()
    energy = total_energy(s.positions, s.velocities, s.masses)
    l_z = angular_momentum(s.positions, s.velocities, s.masses)

    print(f"wrote {path.relative_to(OUTPUT.parent.parent)}  ({len(result.times)} rows)")
    print(f"  sun_earth initial energy            = {energy:.17g}")
    print(f"  sun_earth initial angular momentum  = {l_z:.17g}  (+z)")
    print(f"  final energy drift                  = {np.max(result.energy_drift):.3e}")


if __name__ == "__main__":
    main()
