"""Export a reference trajectory for the C++ engine to be validated against.

    ./venv/bin/python -m validation.export_reference           # write
    ./venv/bin/python -m validation.export_reference --check   # verify only

Writes tests/data/reference_trajectory.csv, which tests/cpp/test_core.cpp
replays. The C++ engine runs the same scenario with the same integrator at the
same timestep and has to reproduce these positions to ~1e-12 AU; anything
larger is a real difference in the physics rather than a rounding artifact.

--check regenerates the trajectory and compares it against the committed file
without writing, so CI can catch reference data that has drifted out of sync
with the Python physics. The comparison is numerical rather than byte-exact:
libm differs between platforms in the last ulp, and a byte comparison would
fail on Linux for a file generated on macOS while telling us nothing.
"""

import argparse
import pathlib
import sys

import numpy as np

from validation.nbody import angular_momentum, total_energy
from validation.scenarios import sun_earth
from validation.simulate import run

# Must match kDt in scenes/orbital/main.cpp and the value in test_core.cpp.
DT = 1.0 / 365.25  # one day, in years
DURATION = 2.0     # years
INTEGRATOR = "verlet"

# Same bound the C++ cross-validation test uses.
TOLERANCE = 1e-12

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "tests" / "data"
PATH = OUTPUT / "reference_trajectory.csv"


def generate():
    """Run the scenario and return (times, trajectory)."""
    scenario = sun_earth()
    result = run(scenario, INTEGRATOR, dt=DT, duration=DURATION)
    return result, len(scenario.masses)


def write(result, n):
    OUTPUT.mkdir(parents=True, exist_ok=True)

    header = ["t"]
    for i in range(n):
        header += [f"x{i}", f"y{i}", f"z{i}"]

    with open(PATH, "w") as f:
        f.write("# generated by validation/export_reference.py -- do not edit\n")
        f.write(f"# integrator={INTEGRATOR} dt={DT!r} duration={DURATION!r}\n")
        f.write(",".join(header) + "\n")

        for step in range(len(result.times)):
            row = [f"{result.times[step]:.17g}"]
            for i in range(n):
                x, y = result.trajectory[step, i]
                row += [f"{x:.17g}", f"{y:.17g}", "0"]  # 2D Python -> 3D C++
            f.write(",".join(row) + "\n")


def read_committed():
    """Positions of body 1 from the committed CSV."""
    rows = []
    with open(PATH) as f:
        for line in f:
            if not line.strip() or line.startswith("#") or line.startswith("t"):
                continue
            values = [float(v) for v in line.split(",")]
            rows.append(values[4:6])  # x1, y1
    return np.array(rows)


def check(result):
    if not PATH.exists():
        print(f"missing {PATH}", file=sys.stderr)
        return 1

    committed = read_committed()
    generated = result.trajectory[:, 1, :]

    if committed.shape != generated.shape:
        print(f"shape mismatch: committed {committed.shape}, "
              f"generated {generated.shape}", file=sys.stderr)
        return 1

    worst = np.max(np.linalg.norm(committed - generated, axis=1))
    print(f"reference data: max divergence {worst:.3e} AU "
          f"(tolerance {TOLERANCE:.0e})")

    if worst > TOLERANCE:
        print("reference data is stale -- rerun without --check and commit",
              file=sys.stderr)
        return 1
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed file instead of writing it")
    args = parser.parse_args()

    result, n = generate()

    if args.check:
        sys.exit(check(result))

    write(result, n)

    # Printed because the C++ diagnostics tests use these as fixtures.
    s = sun_earth()
    energy = total_energy(s.positions, s.velocities, s.masses)
    l_z = angular_momentum(s.positions, s.velocities, s.masses)

    print(f"wrote {PATH.relative_to(OUTPUT.parent.parent)}  ({len(result.times)} rows)")
    print(f"  sun_earth initial energy            = {energy:.17g}")
    print(f"  sun_earth initial angular momentum  = {l_z:.17g}  (+z)")
    print(f"  final energy drift                  = {np.max(result.energy_drift):.3e}")


if __name__ == "__main__":
    main()
